defaults:
  - _self_

hydra:
  run:
    dir: "."

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  image_folder: data/raw/images/train

api_info:
  url: https://public.nord.bazo.dk/v1/articles
  max_per_page: 100

dataset_names:
  summary: summary
  image_caption: image_caption

sleeps:
  short: 5
  medium: 60
  long: 900

testing: False
timeout: 60
n_requests_image: 2

